builds:
- binary: spli
  main: .
  ldflags: -s -w -X=github.com/cicd-toolkit/spli.version={{.Version}}
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
archives:
- name_template: "{{ .ProjectName }}-{{ if eq .Os \"darwin\" }}mac{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}"
  format: binary
