name: test
on:
    pull_request:
      branches:
        - master
jobs:

  run:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Check out code
      uses: actions/checkout@v3

    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Run tests
      run: make test
