name: test
on: push
jobs:

  run:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Check out code
      uses: actions/checkout@v3

    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Run unit tests
      run: make test-unit
