name: test
on:
    pull_request:
      branches:
        - master
jobs:

  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [9.3.0, 9.2.2, 9.1.3, 8.2.0]
    services:
      splunk:
        image: splunk/splunk:${{ matrix.version }}
        env:
          SPLUNK_START_ARGS: --answer-yes --no-prompt --accept-license
          SPLUNK_PASSWORD: Admin-1234
          DEBUG: true
        options: >-
          --health-interval 30s
          --health-timeout 5s
          --health-retries 5
          --name splunk
        ports:
          - 8000:8000
          - 8088:8088
          - 8089:8089
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Check out code
      uses: actions/checkout@v3

    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download


    - name: Create local config
      run: |
        mkdir ~/.spli
        cat <<EOL > ~/.spli/config
        [default]
        host                = localhost
        admin_port          = 8089
        web_port            = 8000
        protocol            = http
        EOL


    - name: Run tests
      run: |
        make test
      env:
        SPLUNK_VERSION: ${{ matrix.version }}
        SPLUNK_USERNAME: "admin"
        SPLUNK_PASSWORD: "Admin-1234"
